// AngularApp/src/app/components/edit-user/edit-user.component.ts
import { Component, OnInit } from '@angular/core';
import { UserService } from '../../service/user.service'
import { Router, ActivatedRoute, Params } from '@angular/router'
import { User } from '../../model/user.model'
import { FormBuilder, FormGroup, Validators} from '@angular/forms'
import { Store } from '@ngxs/store'

@Component({
  selector: 'app-edit-user',
  templateUrl: './edit-user.component.html',
  styleUrls: ['./edit-user.component.css']
})
export class EditUserComponent implements OnInit {
  
  user : User
  editForm : FormGroup


  constructor(
    private store : Store,
    private formBuilder : FormBuilder,
    private router : Router,
    private route : ActivatedRoute,
    private userService : UserService
  ) { }

  ngOnInit() {
    this.editForm = this.formBuilder.group({
      id : [],
      email : ['', Validators.required],
      firstName : ['', Validators.required],
      lastName : ['', Validators.required]
    })

    this.route.params.forEach((params : Params) => {
        let id = params['id']
        if(!id) {
          this.router.navigate(['list-user'])
          return
        }

        this.store.select(state =>
          state.userState.users).subscribe(users =>{
            this.user = users.find(user => user.id == id)
            this.editForm.setValue(this.user)
          })
      })
  
  }

  onSubmit() {
    this.userService.updateUser(this.editForm.value)
      .subscribe(data => {
        this.router.navigate(['list-user'])
      })
  }


}

<div class="col-md-6">
    <h2 class="text-center">Edit User</h2>
    <form [formGroup]="editForm" (ngSubmit)="onSubmit()">
      <div class="form-group">
        <label for="email">Email address:</label>
        <input type="email" formControlName="email" placeholder="Email" name="email" class="form-control" id="email">
      </div>
  
      <div class="form-group">
        <label for="firstName">First Name:</label>
        <input formControlName="firstName" placeholder="First Name" name="firstName" class="form-control" id="firstName">
      </div>
  
      <div class="form-group">
        <label for="lastName">Last Name:</label>
        <input formControlName="lastName" placeholder="Last name" name="lastName" class="form-control" id="lastName">
      </div>
  
      <button class="btn btn-success">Update</button>
    </form>
  </div>

// react-crud/src/component/EditUser.js
import React, { Component } from 'react';

// redux-form : form 쪽 핸들링시 유용
// 유저 입력 데이터르 자동 획득해서 redux 의 reducer 에게
// 저장까지 해준 
import { Field, reduxForm } from 'redux-form';

export class EditUser extends Component {
    url = null
    param = null

    constructor(props) {
        super(props);
        this.handleSubmit = this.handleSubmit.bind(this);
    }

    componentWillMount(){
        this.url = this.props.match.url
        this.param = this.props.match.params.id
    }

    handleSubmit(user) {
        // alert('submit......')
        // this.props.history.push('/add')
        // event.preventDefault();
        this.props.onSubmit(user)
    }
    render() {
        return (
            <div>
                <div className="col-md-6">
                    <h2 className="text-center">
                        {this.url==='/add' ? 'Add User' : 'Update User'}
                    </h2>

                    <form onSubmit={this.props.handleSubmit(this.handleSubmit)}>
                        <div className="form-group">
                            <label>Email address:</label>
                            <Field component="input" placeholder="email" name="email" className="form-control" id="email" />
                        </div>
                        <div className="form-group">
                            <label>First Name:</label>
                            <Field component="input" placeholder="firstName" name="firstName" className="form-control" id="firstName" />
                        </div>
                        <div className="form-group">
                            <label>Last Name:</label>
                            <Field component="input" placeholder="lastName" name="lastName" className="form-control" id="lastName" />
                        </div>
                        <button className="btn btn-success" type="submit">
                        {this.url==='/add' ? 'Add' : 'Update'}
                        </button>
                    </form>
                </div>
            </div>

        )
    }
}
